DROP DATABASE IF EXISTS `reeview`;
CREATE DATABASE  IF NOT EXISTS `reeview` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `reeview`;

DROP TABLE IF EXISTS `control_tables`;

CREATE TABLE `control_tables` (
    -- custom columns
    `LEVEL` VARCHAR (32) DEFAULT NULL,
    `VISIBLE` VARCHAR (3) NOT NULL DEFAULT 'YES',
    `EDITABLE` VARCHAR (3) NOT NULL DEFAULT 'NO',
    `ROLE` VARCHAR (32) NOT NULL,
    -- columns from INFORMATION_SCHEMA
    `TABLE_NAME` VARCHAR (255) NOT NULL,
    `COLUMN_NAME` VARCHAR (255) NOT NULL,
    `COLUMN_DEFAULT` VARCHAR (32) DEFAULT NULL,
    `IS_NULLABLE` VARCHAR (3) NOT NULL,
    `COLUMN_TYPE` VARCHAR (32) NOT NULL,
    `COLUMN_KEY` VARCHAR (3) DEFAULT NULL,
    -- triple key table | column | role
    PRIMARY KEY (`TABLE_NAME`, `COLUMN_NAME`, `ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `reeview`.`control_tables` 
    (`LEVEL`, `VISIBLE`, `EDITABLE`, `ROLE`, `TABLE_NAME`, `COLUMN_NAME`, `COLUMN_DEFAULT`, `IS_NULLABLE`, `COLUMN_TYPE`, `COLUMN_KEY`) 
VALUES
    ('MAPA', 'YES', 'NO', 'admin', 'ac_line_sections', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'ac_line_sections', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'ac_line_sections', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('MAPA', 'YES', 'NO', 'admin', 'ac_line_sections', 'id_line', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'r0', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'x0', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'b0', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'r1', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'x1', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'b1', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'r2', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'x2', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'b2', NULL, 'YES', 'double', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'length', '0', 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'ac_line_sections', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'enom', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'soc_0', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'min_soc', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'batteries', 'max_soc', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'id_bay', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'action', NULL, 'NO', 'tinyint(4)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'name', '"', 'NO', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'number', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'bay', 'id_voltage_level', NULL, 'YES', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'id_bus', 'uuid_v4s()', 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'name', '"', 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'x', '0', 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'y', '0', 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'rotation', '0', 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'is_dc', '0', 'NO', 'tinyint(1)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'secondary_id', NULL, 'NO', 'varchar(48)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses', 'id_bdi', NULL, 'YES', 'varchar(48)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'buses_connectivity_nodes', 'id_bus', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'buses_connectivity_nodes', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'buses_connectivity_nodes', 'id_model', NULL, 'NO', 'varchar(45)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'buses_connectivity_nodes', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'communities', 'id_community', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'communities', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'communities', 'id_country', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'communities', 'id_INE', NULL, 'YES', 'varchar(2)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'name', NULL, 'YES', 'varchar(24)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'x', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes', 'y', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes_voltage_levels', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes_voltage_levels', 'id_voltage_level', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes_voltage_levels', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'connectivity_nodes_voltage_levels', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies', 'id_contingency', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies', 'name', '', 'NO', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_generators', 'id_contingency', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_generators', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_generators', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_sections', 'id_contingency', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_sections', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'contingencies_sections', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'countries', 'id_country', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'countries', 'ISO3', NULL, 'YES', 'varchar(3)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'countries', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'countries', 'ISO2', NULL, 'YES', 'varchar(4)', NULL),
    ('MAPA', 'YES', 'NO', 'admin', 'dc_line_sections', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'dc_line_sections', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'dc_line_sections', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('MAPA', 'YES', 'NO', 'admin', 'dc_line_sections', 'id_line', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('MAPA', 'YES', 'YES', 'admin', 'dc_line_sections', 'r0', NULL, 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'dc_line_sections', 'r1', NULL, 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'dc_line_sections', 'length', NULL, 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'dc_line_sections', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'dynamic_line_rating_devices', 'id_dlr', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'dynamic_line_rating_devices', 'id_section', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'dynamic_line_rating_devices', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'dynamic_line_rating_devices', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'dynamic_line_rating_devices', 'name', NULL, 'YES', 'varchar(64)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'emissions', 'id_emissions', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'emissions', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'fixed_shunts', 'id_shunt', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'fixed_shunts', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'fixed_shunts', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'fixed_shunts', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'active', '1', 'YES', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'g', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'b', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'g1', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'b1', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'rating', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'fixed_shunts', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'fuels', 'id_fuel', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'fuels', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'generation_technologies', 'id_technology', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'generation_technologies', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'generators', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'generators', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'generators', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'generators', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'generators', 'id_connectivity_node_control', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'id_power_plant', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'id_technology', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'secondary_id', NULL, 'YES', 'varchar(48)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'snom', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'p', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'v', '1', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'pf', '0.9', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'pmin', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'pmax', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'qmin', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'qmax', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'r0_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'x0_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'r1_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'x1_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'r2_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'x2_source', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'must_run', NULL, 'YES', 'tinyint(1)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'om_fixed', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'om_variable', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'investment_cost', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'mttf', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'mttr', NULL, 'YES', 'double', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'online_date', NULL, 'YES', 'date', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'offline_date', NULL, 'YES', 'date', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'generators', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'length', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'r', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'loss_factor', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'min_firing_angle_f', '-6.28', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'max_firing_angle_f', '6.28', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'min_firing_angle_t', '-6.28', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'max_firing_angle_t', '6.28', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'vset_f', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'vset_t', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'hvdc', 'Pset', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'impedance_tables', 'id_table', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'impedance_tables', 'name', NULL, 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'impedance_tables_data', 'id_table', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'impedance_tables_data', 'position', NULL, 'NO', 'int(11)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'impedance_tables_data', 'value', NULL, 'NO', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'loads', 'id_load', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'loads', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'loads', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'loads', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'active', '1', 'YES', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'p', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'q', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'loads', 'id_load_type', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'online_date', NULL, 'YES', 'date', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'offline_date', NULL, 'YES', 'date', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'loads', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'loads_types', 'id_load_type', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'loads_types', 'name', '"', 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'idlogs', NULL, 'NO', 'int(11)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'userid', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'table_name', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'attribute', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'old_value', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs', 'new_value', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'log_id', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'user_id', NULL, 'NO', 'varchar(64)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'function_name', NULL, 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'execution_time', NULL, 'NO', 'datetime', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'attribute', NULL, 'NO', 'varchar(64)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'logs_usage', 'attribute_id', NULL, 'NO', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'models', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models', 'valid_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models', 'creation_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models', 'created_by', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models_groups', 'id_model_group', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'models_groups', 'name', '"', 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models_models', 'id_model_parent', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'models_models', 'id_model_child', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'models_models', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'models_models_groups', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'models_models_groups', 'id_model_group', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'owners', 'id_owner', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'owners', 'name', NULL, 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'id_position', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'id_position_type', NULL, 'YES', 'tinyint(4)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'online_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions', 'offline_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions_buses', 'id_position', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_buses', 'id_bus', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_buses', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_sections', 'id_position', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_sections', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_sections', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_sections', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions_types', 'id_position_type', NULL, 'NO', 'tinyint(4)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'positions_types', 'name', NULL, 'NO', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'positions_types', 'comments', NULL, 'YES', 'varchar(256)', NULL),
    ('MAPA', 'YES', 'NO', 'admin', 'power_lines', 'id_line', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'power_lines', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'power_lines', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'power_lines', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'power_lines', 'online_date', NULL, 'YES', 'date', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'power_lines', 'offline_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'id_power_plant', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'online_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'power_plants', 'offline_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'profile_groups', 'id_profile_group', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'profile_groups', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'profiles_', 'id_profile', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'profiles_', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'profiles_', 'id_profile_group', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'profiles_', 'utc_offset', '0', 'NO', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'profiles_', 'file_name', NULL, 'NO', 'varchar(3000)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'provinces', 'id_province', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'provinces', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'provinces', 'id_community', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'provinces', 'id_INE', NULL, 'YES', 'varchar(2)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'id_connectivity_node_1', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'id_connectivity_node_2', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'active', '1', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'rating', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'id_rating_profile', NULL, 'YES', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'contingency_factor1', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'contingency_factor2', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'contingency_factor3', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'online_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'offline_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'mttf', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'mttr', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections', 'sequential', '1', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'section_name1', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'bus_name1', '"', 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'bus_name2', '"', 'NO', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'sid1', NULL, 'NO', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'bid1', 'uuid_v4s()', 'NO', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_bus', 'bid2', 'uuid_v4s()', 'NO', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'id_section_group', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'online_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'offline_date', NULL, 'YES', 'date', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_groups', 'description', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'id_line_location', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'id_model', NULL, 'NO', 'varchar(32)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'id_section', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'sequential_position', NULL, 'NO', 'int(11)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'latitude', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'longitude', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_locations', 'altitude', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'sections_sections_groups', 'id_section_group', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_sections_groups', 'id_section', NULL, 'NO', 'varchar(32)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_sections_groups', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sections_sections_groups', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'r0', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'r1', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'r2', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'x0', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'x1', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'x2', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'series_reactances', 'id_impedance_table', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'ssc', 'id_ssc', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'ssc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'ssc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'ssc', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'ssc', 'name', '"', 'NO', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'ssc', 'vset', '1', 'NO', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'ssc', 'sequential', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'ssc', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'sssc', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'sssc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'sssc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'r0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'x0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'r1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'x1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'vset', '1', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'vset_min', '0.9', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'vset_max', '1.1', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'Pfset', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'P_min', '-99999', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'P_max', '99999', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'Qfset', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'Q_min', '-99999', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'sssc', 'Q_max', '99999', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'sssc', 'id_control_mode', '0', 'NO', 'tinyint(4)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'sssc_control_modes', 'id_control_mode', NULL, 'NO', 'tinyint(4)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'sssc_control_modes', 'name', NULL, 'NO', 'varchar(45)', NULL),
    ('MAPA', 'YES', 'NO', 'admin', 'substations', 'id_substation', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'substations', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('MAPA', 'YES', 'NO', 'admin', 'substations', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'id_zone', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'id_province', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'latitude', NULL, 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'longitude', NULL, 'YES', 'float', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'online_date', NULL, 'YES', 'date', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'offline_date', NULL, 'YES', 'date', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'id_bdi', NULL, 'YES', 'varchar(48)', NULL),
    ('MAPA', 'YES', 'YES', 'admin', 'substations', 'comment', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'svc', 'id_svc', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'svc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'svc', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'svc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'name', '"', 'NO', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'vset', '1', 'NO', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'b_max', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'b_min', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'svc', 'sequential', NULL, 'YES', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switched_shunts', 'id_shunt', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switched_shunts', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switched_shunts', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switched_shunts', 'id_connectivity_node', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'id_table', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'secondary_id', NULL, 'YES', 'varchar(48)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'rating', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'active', '1', 'YES', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'g', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'b', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'online_date', NULL, 'YES', 'datetime', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'offline_date', NULL, 'YES', 'datetime', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switched_shunts', 'sequential', '0', 'YES', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switches', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switches', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'switches', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switches', 'normal_state', '1', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'switches', 'switch_type', '0', 'NO', 'int(11)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'switches_types', 'id_switch_type', NULL, 'NO', 'int(11)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'switches_types', 'name', NULL, 'YES', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'id_tap_changer', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'max_tap_position', NULL, 'YES', 'int(11)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'min_tap_position', NULL, 'YES', 'int(11)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'inc_tap', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'default_tap_position', NULL, 'YES', 'int(11)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'tap_changers', 'current_tap_position', NULL, 'YES', 'int(11)', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'tcsc', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'tcsc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'tcsc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'Kw', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'p_ref', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'T1', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'T2', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'T3', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'Tw', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'xc', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'xl', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'x_max', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'tcsc', 'x_min', '0', 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'thermal_generators', 'heat_rate_base', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'thermal_generators', 'heat_rate_inc', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'YES', 'admin', 'thermal_generators', 'heat_rate_inc2', NULL, 'YES', 'float', NULL),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators_emissions', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators_emissions', 'id_emissions', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators_fuels', 'id_generator', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('VOLTAGE LEVEL', 'YES', 'NO', 'admin', 'thermal_generators_fuels', 'id_fuel', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'r0', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'x0', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'g0', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'b0', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'r1', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'x1', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'g1', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'b1', NULL, 'YES', 'double', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'HVnom', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w', 'LVnom', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_phase_shifters', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_phase_shifters', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_phase_shifters', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'r0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'x0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'g0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'b0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'r1', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'x1', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'g1', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'b1', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'tap_positions', '1', 'YES', 'int(11)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'min_angle', '-6.28', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'max_angle', '6.28', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'default_position', '0', 'YES', 'int(11)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'min_power', '-10000000000', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'max_power', '10000000000', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_phase_shifters', 'HVnom', '1', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_voltage_regulators', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_voltage_regulators', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformers2w_voltage_regulators', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'r0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'x0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'g0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'b0', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'r1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'x1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'g1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'b1', '0', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'tap_positions', '1', 'NO', 'int(11)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'max_ratio', '1.05', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'min_ratio', '0.95', 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'default_position', '0', 'NO', 'int(11)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'min_voltage', '0.9', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'max_voltage', '1.1', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'HVnom', '1', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformers2w_voltage_regulators', 'LVnom', '1', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw', 'id_transformer_nw', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformersnw', 'name', NULL, 'YES', 'varchar(256)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformersnw', 'online_date', NULL, 'YES', 'date', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformersnw', 'offline_date', NULL, 'YES', 'date', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'transformersnw', 'secondary_id', NULL, 'YES', 'varchar(48)', 'UNI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw_windings', 'id_transformer_nw', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw_windings', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'transformersnw_windings', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'vsh', '1', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'Pfset', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'Qfset', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'rl', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'xl', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'bl', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'rs', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'xs', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'rsh', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'xsh', '0', 'NO', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'upfc', 'id_control_mode', '0', 'NO', 'tinyint(4)', 'MUL'),
    (NULL, 'YES', 'TBD', 'admin', 'upfc_control_modes', 'id_control_mode', NULL, 'NO', 'tinyint(4)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'upfc_control_modes', 'name', NULL, 'NO', 'varchar(45)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'voltage_level_configurations', 'id_voltage_level_configuration', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'voltage_level_configurations', 'voltage_level_configuration', NULL, 'NO', 'varchar(64)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'voltage_level_types', 'id_voltage_level_type', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'voltage_level_types', 'voltage_level_type', NULL, 'NO', 'varchar(64)', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'voltage_levels', 'id_voltage_level', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'voltage_levels', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'voltage_levels', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'voltage_levels', 'id_substation', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'id_voltage_level_type', NULL, 'NO', 'varchar(32)', 'MUL'),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'id_voltage_level_configuration', NULL, 'YES', 'varchar(32)', 'MUL'),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'voltage', NULL, 'NO', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'online_date', NULL, 'YES', 'date', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'offline_date', NULL, 'YES', 'date', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'id_bdi', NULL, 'YES', 'varchar(48)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'voltage_levels', 'comment', NULL, 'YES', 'varchar(256)', NULL),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'vsc', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'vsc', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    ('SUBESTACION', 'YES', 'NO', 'admin', 'vsc', 'action', '0', 'NO', 'tinyint(4)', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'r', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'x', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'control_mode', NULL, 'YES', 'int(11)', 'MUL'),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'm', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'm_max', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'm_min', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'theta', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'theta_min', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'theta_max', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'Beq', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'Beq_min', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'Beq_max', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'alpha1', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'alpha2', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'alpha3', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'k', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'kdp', NULL, 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'Pac_set', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'Pdc_set', '0', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'vsc_set', '1', 'YES', 'float', NULL),
    ('SUBESTACION', 'YES', 'YES', 'admin', 'vsc', 'vdc_set', '1', 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'vsc_control_modes', 'id_vsc_control_mode', NULL, 'NO', 'int(11)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'vsc_control_modes', 'name', NULL, 'YES', 'varchar(64)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'id_section', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'id_model', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'action', '0', 'NO', 'tinyint(4)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'r0', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'x0', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'g0', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'b0', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'r1', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'x1', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'g1', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'b1', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'r2', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'x2', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'g2', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'b2', NULL, 'YES', 'double', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'Vnomf', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'windings', 'Vnomt', NULL, 'YES', 'float', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'zones', 'id_zone', NULL, 'NO', 'varchar(32)', 'PRI'),
    (NULL, 'YES', 'TBD', 'admin', 'zones', 'name', NULL, 'YES', 'varchar(256)', NULL),
    (NULL, 'YES', 'TBD', 'admin', 'zones', 'code', NULL, 'YES', 'varchar(45)', NULL);
